<a href="https://colab.research.google.com/github/Zekaiiz/MSSP-6070-Zekai-Zhang/blob/main/CASE_STUDY_REPORT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
from google.colab import files
uploaded = files.upload()
import pandas as pd
df = pd.read_csv('data_academic_performance.csv')

Saving data_academic_performance.csv to data_academic_performance (1).csv

In [10]:
df.shape

(12411, 45)

In [11]:
df.columns

Index(['COD_S11', 'GENDER', 'EDU_FATHER', 'EDU_MOTHER', 'OCC_FATHER',
       'OCC_MOTHER', 'STRATUM', 'SISBEN', 'PEOPLE_HOUSE', 'Unnamed: 9',
       'INTERNET', 'TV', 'COMPUTER', 'WASHING_MCH', 'MIC_OVEN', 'CAR', 'DVD',
       'FRESH', 'PHONE', 'MOBILE', 'REVENUE', 'JOB', 'SCHOOL_NAME',
       'SCHOOL_NAT', 'SCHOOL_TYPE', 'MAT_S11', 'CR_S11', 'CC_S11', 'BIO_S11',
       'ENG_S11', 'Cod_SPro', 'UNIVERSITY', 'ACADEMIC_PROGRAM', 'QR_PRO',
       'CR_PRO', 'CC_PRO', 'ENG_PRO', 'WC_PRO', 'FEP_PRO', 'G_SC',
       'PERCENTILE', '2ND_DECILE', 'QUARTILE', 'SEL', 'SEL_IHE'],
      dtype='object')

In [53]:
df.head()

,COD_S11,GENDER,EDU_FATHER,EDU_MOTHER,OCC_FATHER,OCC_MOTHER,STRATUM,SISBEN,PEOPLE_HOUSE,Unnamed: 9,...,CC_PRO,ENG_PRO,WC_PRO,FEP_PRO,G_SC,PERCENTILE,2ND_DECILE,QUARTILE,SEL,SEL_IHE
0,SB11201210000129,F,Incomplete Professional Education,Complete technique or technology,Technical or professional level employee,Home,Stratum 4,It is not classified by the SISBEN,Three,NaN,...,71,93,79,181,180,91,5,4,2,2
1,SB11201210000137,F,Complete Secundary,Complete professional education,Entrepreneur,Independent professional,Stratum 5,It is not classified by the SISBEN,Three,NaN,...,86,98,78,201,182,92,5,4,4,4
2,SB11201210005154,M,Not sure,Not sure,Independent,Home,Stratum 2,Level 2,Five,NaN,...,18,43,22,113,113,7,1,1,1,1
3,SB11201210007504,F,Not sure,Not sure,Other occupation,Independent,Stratum 2,It is not classified by the SISBEN,Three,NaN,...,76,80,48,137,157,67,4,3,2,2
4,SB11201210007548,M,Complete professional education,Complete professional education,Executive,Home,Stratum 4,It is not classified by the SISBEN,One,NaN,...,98,100,71,189,198,98,5,4,4,2

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12411 entries, 0 to 12410
Data columns (total 45 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   COD_S11           12411 non-null  object
 1   GENDER            12411 non-null  object
 2   EDU_FATHER        12411 non-null  object
 3   EDU_MOTHER        12411 non-null  object
 4   OCC_FATHER        12411 non-null  object
 5   OCC_MOTHER        12411 non-null  object
 6   STRATUM           12411 non-null  object
 7   SISBEN            12411 non-null  object
 8   PEOPLE_HOUSE      12411 non-null  object
 9   Unnamed: 9        0 non-null      float64
 10  INTERNET          12411 non-null  object
 11  TV                12411 non-null  object
 12  COMPUTER          12411 non-null  object
 13  WASHING_MCH       12411 non-null  object
 14  MIC_OVEN          12411 non-null  object
 15  CAR               12411 non-null  object
 16  DVD               12411 non-null  object
 17  FRESH             12411 non-null  object
 18  PHONE             12411 non-null  object
 19  MOBILE            12411 non-null  object
 20  REVENUE           12411 non-null  object
 21  JOB               12411 non-null  object
 22  SCHOOL_NAME       12411 non-null  object
 23  SCHOOL_NAT        12411 non-null  object
 24  SCHOOL_TYPE       12411 non-null  object
 25  MAT_S11           12411 non-null  int64
 26  CR_S11            12411 non-null  int64
 27  CC_S11            12411 non-null  int64
 28  BIO_S11           12411 non-null  int64
 29  ENG_S11           12411 non-null  int64
 30  Cod_SPro          12411 non-null  object
 31  UNIVERSITY        12411 non-null  object
 32  ACADEMIC_PROGRAM  12411 non-null  object
 33  QR_PRO            12411 non-null  int64
 34  CR_PRO            12411 non-null  int64
 35  CC_PRO            12411 non-null  int64
 36  ENG_PRO           12411 non-null  int64
 37  WC_PRO            12411 non-null  int64
 38  FEP_PRO           12411 non-null  int64
 39  G_SC              12411 non-null  int64
 40  PERCENTILE        12411 non-null  int64
 41  2ND_DECILE        12411 non-null  int64
 42  QUARTILE          12411 non-null  int64
 43  SEL               12411 non-null  int64
 44  SEL_IHE           12411 non-null  int64
dtypes: float64(1), int64(17), object(27)
memory usage: 4.3+ MB

In [19]:
df.describe

<bound method NDFrame.describe of                 COD_S11 GENDER                         EDU_FATHER  \
0      SB11201210000129      F  Incomplete Professional Education
1      SB11201210000137      F                 Complete Secundary
2      SB11201210005154      M                           Not sure
3      SB11201210007504      F                           Not sure
4      SB11201210007548      M    Complete professional education
...                 ...    ...                                ...
12406  SB11201420568705      M                            Ninguno
12407  SB11201420573045      M    Complete professional education
12408  SB11201420578809      M   Complete technique or technology
12409  SB11201420578812      F    Complete professional education
12410  SB11201420583232      M                 Complete Secundary

                             EDU_MOTHER  \
0      Complete technique or technology
1       Complete professional education
2                              Not sure
3                              Not sure
4       Complete professional education
...                                 ...
12406                Complete Secundary
12407                Complete Secundary
12408  Complete technique or technology
12409   Complete professional education
12410                 Complete primary

                                     OCC_FATHER                   OCC_MOTHER  \
0      Technical or professional level employee                         Home
1                                 Entrepreneur      Independent professional
2                                   Independent                         Home
3                              Other occupation                  Independent
4                                     Executive                         Home
...                                         ...                          ...
12406                          Other occupation  Auxiliary or Administrative
12407                                 Executive             Other occupation
12408                                   Retired                         Home
12409                  Independent professional          Small entrepreneur
12410                               Independent                         Home

         STRATUM                              SISBEN PEOPLE_HOUSE  Unnamed: 9  \
0      Stratum 4  It is not classified by the SISBEN        Three         NaN
1      Stratum 5  It is not classified by the SISBEN        Three         NaN
2      Stratum 2                             Level 2         Five         NaN
3      Stratum 2  It is not classified by the SISBEN        Three         NaN
4      Stratum 4  It is not classified by the SISBEN          One         NaN
...          ...                                 ...          ...         ...
12406  Stratum 2  It is not classified by the SISBEN          Six         NaN
12407  Stratum 2                             Level 2         Five         NaN
12408  Stratum 2                             Level 2         Five         NaN
12409  Stratum 3  It is not classified by the SISBEN        Seven         NaN
12410  Stratum 3                             Level 1         Four         NaN

       ... CC_PRO ENG_PRO WC_PRO FEP_PRO G_SC PERCENTILE 2ND_DECILE QUARTILE  \
0      ...     71      93     79     181  180         91          5        4
1      ...     86      98     78     201  182         92          5        4
2      ...     18      43     22     113  113          7          1        1
3      ...     76      80     48     137  157         67          4        3
4      ...     98     100     71     189  198         98          5        4
...    ...    ...     ...    ...     ...  ...        ...        ...      ...
12406  ...     86      87     65     142  176         88          5        4
12407  ...     44      11      0     127  107          4          1        1
12408  ...     90      81     87     192  188         95          5        4
12409  ...     51       8     42     121  146         50          3        3
12410  ...     91      79     47     193  178         89          5        4

      SEL SEL_IHE
0       2       2
1       4       4
2       1       1
3       2       2
4       4       2
...    ..     ...
12406   2       2
12407   4       2
12408   2       2
12409   3       2
12410   2       4

[12411 rows x 45 columns]>

In [12]:
df = df[['GENDER', 'EDU_FATHER', 'EDU_MOTHER', 'SISBEN', 'STRATUM',
         'MAT_S11', 'CR_S11', 'CC_S11', 'BIO_S11', 'ENG_S11',
         'QR_PRO', 'CR_PRO', 'CC_PRO', 'WC_PRO', 'ENG_PRO']]
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12411 entries, 0 to 12410
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   GENDER      12411 non-null  object
 1   EDU_FATHER  12411 non-null  object
 2   EDU_MOTHER  12411 non-null  object
 3   SISBEN      12411 non-null  object
 4   STRATUM     12411 non-null  object
 5   MAT_S11     12411 non-null  int64
 6   CR_S11      12411 non-null  int64
 7   CC_S11      12411 non-null  int64
 8   BIO_S11     12411 non-null  int64
 9   ENG_S11     12411 non-null  int64
 10  QR_PRO      12411 non-null  int64
 11  CR_PRO      12411 non-null  int64
 12  CC_PRO      12411 non-null  int64
 13  WC_PRO      12411 non-null  int64
 14  ENG_PRO     12411 non-null  int64
dtypes: int64(10), object(5)
memory usage: 1.4+ MB

GENDER        0
EDU_FATHER    0
EDU_MOTHER    0
SISBEN        0
STRATUM       0
MAT_S11       0
CR_S11        0
CC_S11        0
BIO_S11       0
ENG_S11       0
QR_PRO        0
CR_PRO        0
CC_PRO        0
WC_PRO        0
ENG_PRO       0
dtype: int64

1. Does parental education influence outcomes?

In [69]:
df.groupby('EDU_FATHER')[['MAT_S11', 'QR_PRO', 'CR_S11', 'CR_PRO', 'CC_S11', 'CC_PRO', 'ENG_S11', 'ENG_PRO']].median()

,MAT_S11,QR_PRO,CR_S11,CR_PRO,CC_S11,CC_PRO,ENG_S11,ENG_PRO
EDU_FATHER,,,,,,,,
0,58.0,81.0,57.0,58.0,57.0,54.0,54.0,64.0
Complete Secundary,61.0,82.0,59.0,63.0,59.0,60.0,55.0,68.0
Complete primary,60.0,80.0,57.0,59.0,58.0,57.0,53.0,58.0
Complete professional education,67.0,88.0,62.0,73.0,62.0,71.0,65.0,82.0
Complete technique or technology,64.0,86.0,61.0,71.0,60.0,66.0,60.0,75.0
Incomplete Professional Education,65.0,88.0,62.0,74.0,61.0,71.0,64.0,81.0
Incomplete Secundary,60.0,81.0,58.0,61.0,59.0,56.0,54.0,64.0
Incomplete primary,60.0,80.0,58.0,60.0,58.0,58.0,54.0,60.0
Incomplete technical or technological,63.0,84.0,61.0,70.0,59.0,65.0,58.0,73.0
Ninguno,60.0,79.0,58.0,65.0,58.0,59.0,54.0,66.0
Not sure,61.0,82.0,60.0,60.0,60.0,59.0,58.0,73.0
Postgraduate education,72.0,93.0,66.0,82.0,65.0,80.0,76.0,91.0

In [68]:
df.groupby('EDU_MOTHER')[['MAT_S11', 'QR_PRO', 'CR_S11', 'CR_PRO', 'CC_S11', 'CC_PRO', 'ENG_S11', 'ENG_PRO']].median()

,MAT_S11,QR_PRO,CR_S11,CR_PRO,CC_S11,CC_PRO,ENG_S11,ENG_PRO
EDU_MOTHER,,,,,,,,
0,58.0,80.0,57.0,57.5,57.0,56.0,54.0,63.5
Complete Secundary,61.0,82.0,59.0,63.0,59.0,60.0,55.0,67.0
Complete primary,59.0,79.0,57.0,60.0,58.0,57.0,53.0,58.0
Complete professional education,67.0,89.0,62.0,74.0,62.0,72.0,67.0,83.0
Complete technique or technology,64.0,85.0,61.0,69.0,60.0,66.0,60.0,75.0
Incomplete Professional Education,65.0,88.0,62.0,74.0,62.0,67.0,62.0,80.0
Incomplete Secundary,60.0,80.0,58.0,58.0,58.0,56.0,54.0,63.0
Incomplete primary,60.0,80.0,58.0,61.0,58.0,55.0,53.0,57.0
Incomplete technical or technological,64.0,85.0,62.0,68.0,60.0,64.0,59.0,76.0
Ninguno,64.5,81.5,56.5,47.5,58.0,54.5,54.0,56.5
Not sure,60.0,83.0,61.0,61.0,58.0,59.0,58.0,74.0
Postgraduate education,70.0,92.0,65.0,81.0,64.0,79.0,73.0,90.0

In [67]:
df.groupby('EDU_MOTHER')[['MAT_S11', 'QR_PRO', 'CR_S11', 'CR_PRO', 'CC_S11', 'CC_PRO', 'ENG_S11', 'ENG_PRO']].median().median(axis=1)

EDU_MOTHER
0                                        57.25
Complete Secundary                       60.50
Complete primary                         58.00
Complete professional education          69.50
Complete technique or technology         65.00
Incomplete Professional Education        66.00
Incomplete Secundary                     58.00
Incomplete primary                       58.00
Incomplete technical or technological    64.00
Ninguno                                  56.50
Not sure                                 60.50
Postgraduate education                   76.00
dtype: float64

In [66]:
df.groupby('EDU_FATHER')[['MAT_S11', 'QR_PRO', 'CR_S11', 'CR_PRO', 'CC_S11', 'CC_PRO', 'ENG_S11', 'ENG_PRO']].median().median(axis=1)

EDU_FATHER
0                                        57.5
Complete Secundary                       60.5
Complete primary                         58.0
Complete professional education          69.0
Complete technique or technology         65.0
Incomplete Professional Education        68.0
Incomplete Secundary                     59.5
Incomplete primary                       59.0
Incomplete technical or technological    64.0
Ninguno                                  59.5
Not sure                                 60.0
Postgraduate education                   78.0
dtype: float64

2. Which groups/stratum performs best? Are there differences between groups/stratums?

In [62]:
df.groupby('STRATUM')[['MAT_S11','CR_S11','CC_S11','BIO_S11','ENG_S11',
                      'QR_PRO','CR_PRO','CC_PRO','WC_PRO','ENG_PRO']].median()

,MAT_S11,CR_S11,CC_S11,BIO_S11,ENG_S11,QR_PRO,CR_PRO,CC_PRO,WC_PRO,ENG_PRO
STRATUM,,,,,,,,,,
0,57.5,54.0,53.0,57.5,51.0,83.5,48.5,53.5,61.0,59.0
Stratum 1,58.0,57.0,57.0,60.0,52.0,76.0,55.0,53.0,50.0,53.0
Stratum 2,61.0,59.0,59.0,62.0,55.0,82.0,63.0,59.0,53.0,66.0
Stratum 3,64.0,62.0,61.0,63.0,60.0,86.0,70.0,66.0,55.0,77.0
Stratum 4,69.0,64.0,64.0,67.0,70.0,91.0,76.0,76.0,64.0,86.0
Stratum 5,72.0,65.0,64.0,70.0,80.0,93.0,81.0,77.0,71.0,93.0
Stratum 6,74.0,66.0,66.0,72.0,82.0,95.0,83.0,81.0,73.0,96.0

In [63]:
df.groupby('STRATUM')[['MAT_S11','CR_S11','CC_S11','BIO_S11','ENG_S11',
                      'QR_PRO','CR_PRO','CC_PRO','WC_PRO','ENG_PRO']].median().median(axis = 1)

STRATUM
0            55.75
Stratum 1    56.00
Stratum 2    60.00
Stratum 3    63.50
Stratum 4    69.50
Stratum 5    74.50
Stratum 6    77.50
dtype: float64

3. How does each gender perform in the global assessment?

In [17]:
gender_assessmnt = df.groupby('GENDER')[['MAT_S11','CR_S11','CC_S11','BIO_S11','ENG_S11',
                      'QR_PRO','CR_PRO','CC_PRO','WC_PRO','ENG_PRO']].median()

gender_assessmnt['global assessment'] = gender_assessmnt.mean(axis=1)

print(gender_assessmnt)

        MAT_S11  CR_S11  CC_S11  BIO_S11  ENG_S11  QR_PRO  CR_PRO  CC_PRO  \
GENDER
F          61.0    61.0    60.0     62.0     59.0    78.0    66.0    63.0
M          65.0    61.0    61.0     65.0     59.0    89.0    69.0    65.0

        WC_PRO  ENG_PRO  global assessment
GENDER
F         60.0     72.0               64.2
M         53.0     76.0               66.3

In [20]:
df['AVG_SCORE'] = df[['MAT_S11', 'CR_S11', 'CC_S11', 'BIO_S11', 'ENG_S11',
                           'QR_PRO', 'CR_PRO', 'CC_PRO', 'WC_PRO', 'ENG_PRO']].mean(axis=1)
df.groupby('GENDER')['AVG_SCORE'].mean()

GENDER
F    62.146282
M    63.847286
Name: AVG_SCORE, dtype: float64